services:
  - docker

script:
  - docker build -t ravi59/doordish .
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push ravi59/doordish
deploy:
  provider: elasticbeanstalk
  region: ap-south-1
  app: doordish
  env: Doordish-env
  bucket-name: elasticbeanstalk-ap-south-1-566658347233
  bucket-path: doordish
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
